### PR TITLE
feat: theme toggler

### PR DESCRIPTION
**Pull request by raj-p26**
- Introduced Themes: Light/Dark using bootstrap.
- Disabled SpellCheck and auto correction from `<Input />` component.
- Added a Back button in Navbar.
- Fixed some issues with navbar.
- Added Light mode/Dark mode icons.
- Made document data fetching Async.
- minor changes.

### CODE REVIEW

**Review by drashtipadia — COMMENTED** [review]
You are Bootstrap Master.....

**Comment by raj-p26** [comment]
I am nothing. :)
Consider this a professional courtesy.

**Comment by drashtipadia** [comment]
> I am nothing. :)
> Consider this a professional courtesy.

No 
You are master of bootstrap..
Intelligent person..

**Comment by raj-p26** [comment]
> > I am nothing. :)
> > Consider this a professional courtesy.
> 
> No You are master of bootstrap.. Intelligent person..

No, I'm a regular kid

**Comment by drashtipadia** [comment]
> > > I am nothing. :)
> > > Consider this a professional courtesy.
> > 
> > No You are master of bootstrap.. Intelligent person..
> 
> No, I'm a regular kid

Nein, This is wrong

**Pull request merged**
